"""
Tool Name: torch2d_segmentation
================================

Description:
    Runs segmentation inference using a deep convolutional neural network (CNN).

Parameters:            
    - input_image (SMImage): Input image for the prediction.
    - model_backbone (str): Currently supported models are defined in models/unet_zoo.py.
    - weights_path (str): Path to the .pth file.
        Be careful not to commit the weights file to the git repo (it is too large).
    - prediction_threshold (float, optional): Applied to the predition map generated by the CNN to obtain a binary segmentation mask. Default = 0.5.
    - num_classes (int, optional): number of class labels to be included in the segmentation prediction. Default=1.
    - model_specific_output_class (int, optional): Class to be returned if multiple classes are included in the segmentation model.
    - map_output_dir (str, optional): Provide this if the prediction map is to be written as a png.
        The filename will be based on the tool name and end with `_map.png`.
    - gpu_num: GPU to be used for computation. Default = 0, i.e., use CPU.

Output:
    - SMImage: Binary segmentation mask.
            
Example JSON Plan:
  "neural_net-torch_seg": {
    "code": "torch2d_segmentation.py",
    "code_learn": "torch2d_segmentation_learn.py",
    "input_image": "from image_preprocessing-clahe",
    "model_backbone": "resnet50",
    "weights_path": "/home/matt/weights/right_lung_weights.pth",
    "num_classes": 1,
    "map_output_dir": "from arg output_dir",
    "learning_rate": 1e-4,
    "batch_size": 16,
    "num_epochs": 100
  }
  
Notes:
    - Uses the pytorch package: https://docs.pytorch.org/docs/stable/
"""

import asyncio
import numpy as np
import os
import warnings
import logging
from einops import rearrange
from PIL import Image

import torch
from models import *
import torch.nn.functional as F

from sm_sample_processor import SMSampleProcessor
from sm_image import SMImage
from sm_sample_id import SMSampleID

# Suppress benign warnings about unexpected keys when loading adapted pretrained weights.
warnings.filterwarnings("ignore", message=".*Unexpected key.*")
warnings.filterwarnings("ignore", message=".*Unexpected keys.*")
logging.getLogger("timm").setLevel(logging.ERROR)

class Torch2DSegmentation(SMSampleProcessor):

    async def setup(
        self, 
        *, 
        model_backbone: str,
        weights_path:str,
        num_classes: int = 1,
        gpu_num: int = 0
    ) -> None:
        if float(gpu_num) < 0:
            self.device = torch.device("cpu")
        else:
            self.device = torch.device("cuda:"+str(gpu_num) if torch.cuda.is_available() else "cpu")

        self.model = unet_zoo.Model(
            backbone=model_backbone,    # backbone network name
            in_channels=1,              # input channels (1 for gray-scale images, 3 for RGB, etc.)
            num_classes=num_classes,    # output channels (number of classes in your dataset)
        )

        self.model = self.model.to(self.device)
        state_dict = torch.load(weights_path, map_location=self.device)
        new_state_dict = {}
        for key, value in state_dict.items():
            new_key = key.replace("module.", "")
            new_state_dict[new_key] = value
        with warnings.catch_warnings():
            warnings.filterwarnings("ignore", message=".*Unexpected key.*")
            warnings.filterwarnings("ignore", message=".*Unexpected keys.*")
            self.model.load_state_dict(new_state_dict, strict=False)
        self.model.eval()
        
        return None


    async def execute(
        self,
        *,
        input_image: SMImage,
        model_specific_output_class: int = -1,
        prediction_threshold: float = 0.5,
        map_output_dir: str = None,
        sample_id: SMSampleID
    ) -> SMImage:

        if input_image is None:
            return None
        
        image_array = input_image.pixel_array.astype(np.float32)[:, 0, :, :] # C Z Y X -> C Y X
        # image_array = input_image.pixel_array.astype(np.float32)[0:1] # h w

        rearranged_image = rearrange(image_array, 'c h w -> 1 c h w') # b c h w : model input type
        rearranged_image = torch.from_numpy(rearranged_image).to(self.device)
        
        pred_mask_image = self.model(rearranged_image) # prediction, then convert it to a list
        pred_map = F.sigmoid(pred_mask_image)
        
        if model_specific_output_class >= 0:
            pred_map = pred_map[:, model_specific_output_class, :, :]

        # Binarize the prediction
        pred_map = np.expand_dims(pred_map.squeeze().cpu().detach().numpy(), 0)
        pred_mask = ((pred_map>prediction_threshold)*1).astype('uint8')
        pred_mask_image = SMImage(input_image.metadata, pred_mask, input_image.label_array)
        
        if map_output_dir is not None:
            rescaled_map = np.squeeze(pred_map)
            if len(rescaled_map.shape) == 2:
                rescaled_map = rescaled_map * 255
                rescaled_map = np.round(rescaled_map).astype(np.uint8)

                with Image.fromarray(np.squeeze(rescaled_map)) as im:
                    fname = self.name()+"_map.png"
                    fname = fname.replace(f"-{self.plan_id}", "")
                    fp = self.sample_output_path(self.resolve_output_dir(map_output_dir, sample_id.dataset), sample_id)
                    fp = os.path.join(fp, fname)
                    # self.print_log(f"fp = {fp}", sample_id)
                    im.save(fp)

        return pred_mask_image


if __name__ == "__main__":   
    tool = Torch2DSegmentation()
    asyncio.run(tool.main())
