"""
Controller: upload_listen
=================================

Description:
    A Core dataset uploader.
        It accepts a csv file containing paths to files to be uploaded to the Blackboard.
        It listens for results and processes them.

Arguments:            
    - dataset_csv: path to csv containing file paths of the dataset
        The csv format is defined in upload_dataset.py.
    - listen_tags: determine which messages are used to obtain results
    - listen_type (optional): Known types that can be deserialized are "dict", "np.ndarray"
        If not provided, tags will be examined to attempt to determine the type
    - addr (optional): Blackboard address. Default: localhost:8080          
    
Example: python upload_listen.py --dataset_csv example_data/biomech_video_masks.csv --addr public-bb.jmh.lol:8080 --listen_tag heel_strike

Notes:
    - Functions are intended to be provided / overloaded: my_data_prep, my_function, my_deserialize.
"""

import asyncio
import argparse
import zlib
from typing import Tuple, Optional

from upload_dataset import random_id, read_serialize_file, create_agent, read_csv, do_upload
from smcore import deserialize

##### Modify this function #####
def my_data_prep(image_path:str, mask_path:str = None) -> Tuple[Optional[bytes], Optional[bytes]]:
    image_data = read_serialize_file(image_path)
    image_data = zlib.compress(image_data)
        
    ##### REPLACE THE CODE ABOVE                                            #####
    ##### Currently image_path is the path to the extracted coordinate csv  #####
    ##### Modify the input csv so image_path is to an input video file      #####
    ##### Then do the pose processing on that video file                    #####
    ##### image_data should be your coordinate csv, serialized as bytes     #####
    ##### (image_data should be the same output type as being generated by the read_serialize_file function)
    ##### mask_data will be none, you don't need to do anything with it     #####
        
    return image_data, None
            
##### Modify this function #####
def my_function(data, sample: int):
    print(f"sample {sample}, result_data: {data}", flush=True)
    
    ##### ADD YOUR CODE HERE                                            #####
    ##### result_data['centroid'] contains the data you need            #####
    ##### sample is the sample number (order of the videos in your CSV) #####
    ##### use the centroid to generate your image overlay               #####

def my_deserialize(serial_data, data_type):
    # Use functions in https://gitlab.com/hoffman-lab/core-py/-/blob/main/src/smcore/deserialize.py?ref_type=heads
    data = None
    if data_type == "dict":
        data = deserialize.dictionary(serial_data)
    elif data_type == "np.ndarray":
        data = deserialize.numpy(serial_data)
    return data
    
async def main(args, data_id: str | None = None):
    if data_id is None:
        data_id = random_id()

    # Create the agent and connect to BB
    agt = await create_agent(args.addr)

    # Read CSV   
    df, num_rows, csv_path = read_csv(args.dataset_csv)
    print(f"Number of CSV rows: {num_rows}", flush=True)
    
    # Post each CSV row
    sample_arg_dict = await do_upload(df, csv_path, data_id, num_rows, my_data_prep, agt)

    # Channel to listen for results
    listen_tags = [f"dataset:{data_id}", "result"]
    if args.listen_tag is not None:
        listen_tags.append(args.listen_tag)
    print(f"listen_tags = {listen_tags}", flush=True)
    listen_ch = await agt.listen_for(listen_tags)
    
    task = agt.start()
    try:
        while True:
            print("listening...")
            result_msg = await listen_ch.get()
            print(f"result_msg tags: {result_msg.tags()}", flush=True)
            
            listen_type = args.listen_type
            if listen_type is None:
                # Try to determine it from the msg tags
                known_types = ["dict", "np.ndarray"]
                for kt in known_types:
                    if kt in result_msg.tags():
                        listen_type = kt
                        break

            sample_tags = [tag for tag in result_msg.tags() if tag.startswith("sample:")]
            if listen_type is not None and len(sample_tags) == 1:
                result_data = my_deserialize(await result_msg.data(), listen_type)
                sample = int(sample_tags[0].split(":", 1)[1])
                my_function(result_data, sample)

    finally:
        task.cancel()
        try:
            await task
        except asyncio.CancelledError:
            pass

        return data_id, sample_arg_dict


if __name__ == "__main__":
    ap = argparse.ArgumentParser(
        prog="upload_listen.py",
        description="a dataset uploader with listener for results",
    )
    ap.add_argument(
        "--dataset_csv",
        help="path to csv file of of file paths"
    )
    ap.add_argument(
        "--listen_tag",
        help="path to csv file of of file paths",
        default=None,
    )
    ap.add_argument(
        "--listen_type",
        help="path to csv file of of file paths",
        default=None,
    )
    ap.add_argument(
        "--addr",
        help="set the blackboard address",
        default="localhost:8080",
    )
    args = ap.parse_args()

    asyncio.run(main(args))

